version: '3.8'

services:
  tomato-duck: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      NODE_ENV: "production"
      MONGODB_URI: ${MONGODB_URI}
      AUTH_SECRET: ${AUTH_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

